### ISSUE TITLE
Dotnetcore.npoi早已停更4年之久

### ISSUE THREAD

**Issue by tonyqus** [chen1tian/ExcelToPdf#1]
Dotnetcore.npoi自2018年就基本不更新了，建议使用NPOI 2.5.5，NPOI自2018年就已经支持.NET Core了，当时的版本是2.4.1。

**Comment by chen1tian** [comment]
当时不太了解这两个库的区别，凭直觉选择了Dotnetcore.npoi。
对于这个项目来说，Dotnetcore.npoi提供的功能已经足够了。如果以今后有功能调整的话，会考虑使用NPOI的。：）

**Comment by chen1tian** [comment]
NPOI功能非常强大，非常感谢NPOI以及作者的付出。辛苦了！
